@startuml
:Usuario: as actor1
:Administrador: as actor2

(Iniciar sesión) as UC1
(Recuperar contraseña) as UC2
(Modificar contraseña) as UC3
(Cerrar sesión) as UC4
(Registrar usuario) as UC5
(Instalar programa) as UC6
actor2 --|> actor1
actor1 -- UC1
actor1 -- UC2
actor1 -- UC3
actor1 -- UC4
actor2 -- UC5
actor2 -- UC6
@enduml